name: OpenELIS-Global-2 CI Build 
on:
  push:
    branches: [develop ,'2.8']
  pull_request:
    branches: [develop ,'2.8']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest   
    steps: 
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11 
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
            ${{ runner.os }}-maven- 
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}         
    - name: Checkout dataexport module
      uses: actions/checkout@v2
      with:
        repository: I-TECH-UW/dataexport
        ref: develop    
    - name: install dataexport module
      run: mvn clean install  
    
    - name: Checkout OpenELIS-Global2
      uses: actions/checkout@v2
      with:
        repository: ${{github.repository}} 
    - name: Build OpenELIS-Global2
      run: mvn clean install  
          
    - name: Run OpenELS image 
      run : docker-compose up -d
      
    - name: Sleep for 3 minutes for OpenELIS to start
      run: sleep 3m
      shell: bash
      
    - name: check containers
      run : docker ps 
      
    - name: Show OpenELIS Logs
      run : docker-compose logs oe.openelis.org
      
