name: OpenELIS-Global-2 CI Build
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  checkFormat-build-unitTest-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Checkout OpenELIS-Global2
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}
          submodules: recursive

      - name: check formatting
        run: mvn spotless:check

      - name: Initialize and build submodules
        run: |
          cd dataexport
          mvn clean install  
          cd ..

      - name: Build OpenELIS-Global2
        run: mvn clean install -Dspotless.check.skip=true

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          badges-directory: target/html/badges

      - name: Publish coverage report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/html/    
